### ISSUE TITLE
Build fails with nightly

### ISSUE THREAD

**Issue by burdges** [canndrew/error_def#3]
Appears the build fails with nightly.  We've noticed this for other syntax extensions like regex_macros repeatedly this summer, so maybe it's related to the MIR changes.  If MIR changes are too tumultuous for syntax extensions to track right now, then maybe it's worth simply noting what versions should work right now.  

We noticed that `rustup.sh --channel=nightly --date=2016-06-23` builds error_def but not some other syntax extensions, btw.

**Comment by canndrew** [comment]
Thanks. This library breaks every couple of months when they change things in libsyntax. It'll be great when procedural macros are stable but I doubt that'll be for another year at least.

I'll try and figure out what they changed and get the library building again asap.

**Comment by canndrew** [comment]
Fixed in 0.3.10, should be on crates.io soon.
