### ISSUE TITLE
Nightly build fails again

### ISSUE THREAD

**Issue by ghost** [canndrew/error_def#4]
Looks like https://github.com/canndrew/error_def/issues/3 is back, on rustc 1.17.0-nightly (0e7727795 2017-02-19):

```
cargo/registry/src/github.com-1ecc6299db9ec823/error_def-0.3.11/src/lib.rs:11:34
   |
11 | use syntax::parse::token::{self, intern, Token, Lit, InternedString, DelimToken,
   |                                  ^^^^^^ no `intern` in `parse::token`
```

And so on. To replicate, just put `#[macro_use] extern crate error_def;` in a file to be compiled.

**Comment by canndrew** [comment]
Sorry, I've let this get several months out of date. I'll fix it up tomorrow.

Thanks for the report!

**Comment by canndrew** [comment]
This should be fixed now. Version 0.3.12 published to crates.io.

**Comment by ghost** [comment]
Thanks for the fast turnaround! I'll give it a shot.
