### ISSUE TITLE
Compile errors on rustc 1.19.0-nightly (01951a61a 2017-05-20)

### ISSUE THREAD

**Issue by kornelski** [canndrew/error_def#5]
Thanks for the crate. It would have been a great time saver, but unfortunately unstable rust is unstable:

> error[E0432]: unresolved import `syntax::codemap::spanned`
 --> /Users/porneL/.cargo/registry/src/github.com-1ecc6299db9ec823/error_def-0.3.12/src/lib.rs:8:29
  |
8 | use syntax::codemap::{Span, spanned, DUMMY_SP, dummy_spanned, Spanned};
  |                             ^^^^^^^ no `spanned` in `codemap`. Did you mean to use `Spanned`?

> error[E0425]: cannot find function `tts_to_parser` in module `parse`
  --> /Users/porneL/.cargo/registry/src/github.com-1ecc6299db9ec823/error_def-0.3.12/src/lib.rs:45:27
   |
45 |   let mut parser = parse::tts_to_parser(cx.parse_sess(), tokens);
   |                           ^^^^^^^^^^^^^ not found in `parse`

etc., etc.

**Comment by canndrew** [comment]
Thanks for the bug report! Should be all fixed now, version 0.3.13 on crates.io.
